#pragma once

#include "general_board_manager.h"

/* templates */
const block_type_t board_initialization_template[BOARD_HEIGHT][BOARD_WIDTH] = {
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_BLUE, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_RED, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_EMPTY},
    {BLOCK_TYPE_ORANGE, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_EMPTY, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN},
    {BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_EMPTY, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN},
    {BLOCK_TYPE_YELLOW, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_EMPTY, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN},
    {BLOCK_TYPE_GREEN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_EMPTY, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN},
    {BLOCK_TYPE_PURPLE, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_EMPTY, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN, BLOCK_TYPE_CYAN},
};
