//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_p131_H
#define METASPRITE_p131_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define p131_TILE_ORIGIN 0
#define p131_TILE_W 8
#define p131_TILE_H 8
#define p131_WIDTH 8
#define p131_HEIGHT 8
#define p131_TILE_COUNT 35
#define p131_PALETTE_COUNT 2
#define p131_COLORS_PER_PALETTE 4
#define p131_TOTAL_COLORS 8
#define p131_MAP_ATTRIBUTES p131_map_attributes
#define p131_MAP_ATTRIBUTES_WIDTH 7
#define p131_MAP_ATTRIBUTES_HEIGHT 5
#define p131_MAP_ATTRIBUTES_PACKED_WIDTH 7
#define p131_MAP_ATTRIBUTES_PACKED_HEIGHT 5

BANKREF_EXTERN(p131)

extern const palette_color_t p131_palettes[8];
extern const uint8_t p131_tiles[560];

extern const unsigned char p131_map[35];
extern const unsigned char p131_map_attributes[35];

#endif
