//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_p121_H
#define METASPRITE_p121_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define p121_TILE_ORIGIN 0
#define p121_TILE_W 8
#define p121_TILE_H 8
#define p121_WIDTH 56
#define p121_HEIGHT 40
#define p121_TILE_COUNT 35
#define p121_PALETTE_COUNT 2
#define p121_COLORS_PER_PALETTE 4
#define p121_TOTAL_COLORS 8
#define p121_MAP_ATTRIBUTES p121_map_attributes
#define p121_MAP_ATTRIBUTES_WIDTH 7
#define p121_MAP_ATTRIBUTES_HEIGHT 5
#define p121_MAP_ATTRIBUTES_PACKED_WIDTH 7
#define p121_MAP_ATTRIBUTES_PACKED_HEIGHT 5

BANKREF_EXTERN(p121)

extern const palette_color_t p121_palettes[8];
extern const uint8_t p121_tiles[560];

extern const unsigned char p121_map_attributes[35];

#endif
